import type {
  AssistantResponse,
  BusinessImpact,
  EvidenceRecord,
  GraphEdge,
  GraphNode,
  Incident,
  IncidentEvent,
  Recommendation,
  ReplayStage,
  SimulationResult,
} from './types';

const incidentDate = '2026-07-24';
const at = (time: string) => `${incidentDate}T${time}:00Z`;

export const incidents: Incident[] = [
  {
    id: 'INC-2407-001',
    title: 'Yield degradation',
    plant: 'Plant Mumbai-1',
    line: 'Assembly Line 3',
    product: 'Precision Bearing P-440',
    batchId: 'B-2407-184',
    severity: 'high',
    status: 'investigating',
    detectedAt: at('11:47'),
    baselineYield: 96,
    currentYield: 82,
    exposureInr: 1800000,
    summary: 'Yield fell 14 points after an extended queue delay, environmental drift, and final-inspection defects.',
  },
  {
    id: 'INC-2407-002',
    title: 'Conveyor cycle drift',
    plant: 'Plant Mumbai-1',
    line: 'Packaging Line 2',
    product: 'Bearing Kit K-22',
    batchId: 'B-2407-191',
    severity: 'medium',
    status: 'monitoring',
    detectedAt: at('12:14'),
    baselineYield: 97,
    currentYield: 94.8,
    exposureInr: 320000,
    summary: 'Cycle time rose 11% above the shift baseline; output remains within the release threshold.',
  },
  {
    id: 'INC-2407-003',
    title: 'Temperature excursion',
    plant: 'Plant Pune-2',
    line: 'Heat Treatment 1',
    product: 'Drive Ring D-18',
    batchId: 'B-2407-204',
    severity: 'low',
    status: 'open',
    detectedAt: at('12:38'),
    baselineYield: 95,
    currentYield: 94.2,
    exposureInr: 120000,
    summary: 'A short furnace-zone excursion was detected and awaits engineering review.',
  },
];

export const featuredIncident = incidents[0];

export const incidentEvents: IncidentEvent[] = [
  {
    id: 'evt_2287',
    timestamp: at('08:00'),
    offsetMinutes: 0,
    label: 'Batch started',
    category: 'system',
    severity: 'info',
    source: 'MES',
    recordId: 'batch:B-2407-184',
    stageId: 'stage-intake',
    graphNodeIds: ['node_material'],
    evidenceIds: ['evidence-batch-start'],
    confidence: 1,
    value: 'Route initialized',
    description: 'Batch B-2407-184 entered Assembly Line 3 with certified EN31 bearing steel.',
  },
  {
    id: 'evt_2288',
    timestamp: at('08:05'),
    offsetMinutes: 5,
    label: 'Intake complete',
    category: 'system',
    severity: 'info',
    source: 'MES',
    recordId: 'evt:INTAKE-2407',
    stageId: 'stage-intake',
    graphNodeIds: ['node_material'],
    evidenceIds: ['evidence-material'],
    confidence: 0.98,
    value: 'Material within specification',
    description: 'Supplier lot passed intake checks; material quality is not a strong causal candidate.',
  },
  {
    id: 'evt_2289',
    timestamp: at('08:20'),
    offsetMinutes: 20,
    label: 'Machine A complete',
    category: 'system',
    severity: 'info',
    source: 'MES',
    recordId: 'evt:MCHA-2407',
    stageId: 'stage-machine-a',
    graphNodeIds: [],
    evidenceIds: ['evidence-machine-a'],
    confidence: 0.99,
    value: '15 min cycle',
    description: 'Turning completed within normal speed, feed, and temperature ranges.',
  },
  {
    id: 'evt_2290',
    timestamp: at('08:51'),
    offsetMinutes: 51,
    label: 'Humidity increased',
    category: 'sensor',
    severity: 'warning',
    source: 'IoT sensors',
    recordId: 'sensor:HUM-2407-51',
    stageId: 'stage-queue',
    graphNodeIds: ['node_humidity', 'node_queue_delay'],
    evidenceIds: ['evidence-humidity'],
    confidence: 0.88,
    value: '68.5% RH',
    description: 'Queue-area humidity exceeded the 60% storage threshold.',
  },
  {
    id: 'evt_2291',
    timestamp: at('11:38'),
    offsetMinutes: 218,
    label: 'Queue delay exceeded 3h',
    category: 'queue',
    severity: 'critical',
    source: 'MES dispatch',
    recordId: 'evt:Q-2407-001',
    stageId: 'stage-queue',
    graphNodeIds: ['node_queue_delay', 'node_temp_drift'],
    evidenceIds: ['evidence-queue', 'evidence-queue-sim'],
    confidence: 0.96,
    value: '198 min wait',
    description: 'Wait time reached 198 minutes against a 30-minute target and became the dominant controllable factor.',
  },
  {
    id: 'evt_2292',
    timestamp: at('11:40'),
    offsetMinutes: 220,
    label: 'Temperature drift',
    category: 'maintenance',
    severity: 'warning',
    source: 'Maintenance',
    recordId: 'alert:MA-2407-013',
    stageId: 'stage-machine-7',
    graphNodeIds: ['node_temp_drift', 'node_machine_7'],
    evidenceIds: ['evidence-temp'],
    confidence: 0.82,
    value: '31.4°C',
    description: 'Machine 7 temperature rose above 28°C after the extended ambient wait.',
  },
  {
    id: 'evt_2293',
    timestamp: at('11:42'),
    offsetMinutes: 222,
    label: 'Machine 7 vibration',
    category: 'maintenance',
    severity: 'critical',
    source: 'Maintenance',
    recordId: 'alert:MA-2407-012',
    stageId: 'stage-machine-7',
    graphNodeIds: ['node_machine_7', 'node_quality_failure'],
    evidenceIds: ['evidence-machine-7', 'evidence-machine-sim'],
    confidence: 0.61,
    value: '4.7 mm/s',
    description: 'Vibration exceeded its threshold, but replacement-only simulation produces limited recovery.',
  },
  {
    id: 'evt_2294',
    timestamp: at('11:45'),
    offsetMinutes: 225,
    label: 'Dimensional defect',
    category: 'inspection',
    severity: 'critical',
    source: 'Quality',
    recordId: 'defect:DEF-2407-041',
    stageId: 'stage-inspection',
    graphNodeIds: ['node_temp_drift', 'node_quality_failure'],
    evidenceIds: ['evidence-defect-dimensional'],
    confidence: 0.97,
    value: '+0.08 mm',
    description: 'Bore diameter exceeded tolerance; thermal expansion is the leading mechanism.',
  },
  {
    id: 'evt_2295',
    timestamp: at('11:46'),
    offsetMinutes: 226,
    label: 'Surface finish defect',
    category: 'inspection',
    severity: 'critical',
    source: 'Quality',
    recordId: 'defect:DEF-2407-042',
    stageId: 'stage-inspection',
    graphNodeIds: ['node_machine_7', 'node_quality_failure'],
    evidenceIds: ['evidence-defect-surface'],
    confidence: 0.95,
    value: 'Ra 0.62 μm',
    description: 'Surface roughness exceeded the 0.40 μm specification.',
  },
  {
    id: 'evt_2296',
    timestamp: at('11:47'),
    offsetMinutes: 227,
    label: 'Batch rejected',
    category: 'inspection',
    severity: 'critical',
    source: 'Quality',
    recordId: 'inspection:INSP-2407-184',
    stageId: 'stage-inspection',
    graphNodeIds: ['node_quality_failure'],
    evidenceIds: ['evidence-inspection'],
    confidence: 1,
    value: 'Yield 82%',
    description: 'Quality score fell to 62.3/100 and the batch was rejected.',
  },
];

export const replayStages: ReplayStage[] = [
  {
    id: 'stage-intake',
    label: 'Raw material intake',
    shortLabel: 'Intake',
    status: 'ok',
    startMinute: 0,
    endMinute: 5,
    summary: 'Certified material entered the line inside intake limits.',
    inputs: ['Lot LOT-SUP-2407-88', 'EN31 bearing steel'],
    outputs: ['Intake inspection passed'],
    metrics: [
      { label: 'Humidity', value: '48.0%', state: 'normal' },
      { label: 'Temperature', value: '22.5°C', state: 'normal' },
    ],
    eventIds: ['evt_2287', 'evt_2288'],
  },
  {
    id: 'stage-machine-a',
    label: 'Machine A — Turning',
    shortLabel: 'Machine A',
    status: 'ok',
    startMinute: 5,
    endMinute: 20,
    summary: 'Turning completed normally with no contributing anomaly.',
    inputs: ['Intake-cleared material'],
    outputs: ['Turned component'],
    metrics: [
      { label: 'Cycle', value: '15 min', state: 'normal' },
      { label: 'Speed', value: '1,200 rpm', state: 'normal' },
    ],
    eventIds: ['evt_2289'],
  },
  {
    id: 'stage-queue',
    label: 'Queue — Waiting for Machine B',
    shortLabel: 'Queue',
    status: 'warning',
    startMinute: 20,
    endMinute: 218,
    summary: 'The batch waited 198 minutes in elevated humidity, creating the primary intervention opportunity.',
    inputs: ['Turned component', 'Queue target 30 min'],
    outputs: ['Environmentally exposed component'],
    metrics: [
      { label: 'Wait', value: '198 min', state: 'critical' },
      { label: 'Humidity', value: '68.5%', state: 'warning' },
    ],
    eventIds: ['evt_2290', 'evt_2291'],
  },
  {
    id: 'stage-machine-7',
    label: 'Machine 7 — Grinding',
    shortLabel: 'Machine 7',
    status: 'warning',
    startMinute: 218,
    endMinute: 222,
    summary: 'Temperature and vibration alarms appeared, but counterfactual evidence limits their causal weight.',
    inputs: ['Queue-exposed component'],
    outputs: ['Ground component'],
    metrics: [
      { label: 'Temperature', value: '31.4°C', state: 'warning' },
      { label: 'Vibration', value: '4.7 mm/s', state: 'critical' },
    ],
    eventIds: ['evt_2292', 'evt_2293'],
  },
  {
    id: 'stage-inspection',
    label: 'Quality inspection',
    shortLabel: 'Inspection',
    status: 'failure',
    startMinute: 222,
    endMinute: 227,
    summary: 'Dimensional and surface defects drove the final quality failure.',
    inputs: ['Ground component', 'Inspection criteria'],
    outputs: ['Rejected batch'],
    metrics: [
      { label: 'Quality score', value: '62.3 / 100', state: 'critical' },
      { label: 'Defect rate', value: '18%', state: 'critical' },
    ],
    eventIds: ['evt_2294', 'evt_2295', 'evt_2296'],
  },
  {
    id: 'stage-packaging',
    label: 'Packaging & disposition',
    shortLabel: 'Disposition',
    status: 'failure',
    startMinute: 227,
    endMinute: 229,
    summary: 'Packaging was stopped and the rejected batch was quarantined.',
    inputs: ['Rejected batch'],
    outputs: ['Quarantine record'],
    metrics: [{ label: 'Disposition', value: 'Rejected', state: 'critical' }],
    eventIds: [],
  },
];

export const graphNodes: GraphNode[] = [
  {
    id: 'node_humidity',
    label: 'Humidity rise',
    type: 'environment',
    influence: 0.34,
    confidence: 0.88,
    evidenceType: 'observed_correlation',
    controllable: true,
    source: 'IoT',
    value: '68.5% RH',
    threshold: '60%',
    description: 'Environmental exposure amplified risk during the long wait.',
    eventIds: ['evt_2290'],
    evidenceIds: ['evidence-humidity'],
    position: { x: 10, y: 18 },
  },
  {
    id: 'node_queue_delay',
    label: 'Queue delay',
    type: 'process',
    influence: 0.89,
    confidence: 0.96,
    evidenceType: 'counterfactual_simulated',
    controllable: true,
    source: 'MES',
    value: '198 min',
    threshold: '30 min',
    description: 'The strongest controllable factor; reducing it restores predicted yield to 96%.',
    eventIds: ['evt_2290', 'evt_2291'],
    evidenceIds: ['evidence-queue', 'evidence-queue-sim'],
    position: { x: 37, y: 18 },
  },
  {
    id: 'node_temp_drift',
    label: 'Temperature drift',
    type: 'condition',
    influence: 0.45,
    confidence: 0.82,
    evidenceType: 'model_estimated',
    controllable: false,
    source: 'Maintenance',
    value: '31.4°C',
    threshold: '28°C',
    description: 'A likely mechanism linking the prolonged wait to dimensional variation.',
    eventIds: ['evt_2292', 'evt_2294'],
    evidenceIds: ['evidence-temp', 'evidence-defect-dimensional'],
    position: { x: 64, y: 18 },
  },
  {
    id: 'node_machine_7',
    label: 'Machine 7',
    type: 'equipment',
    influence: 0.18,
    confidence: 0.61,
    evidenceType: 'counterfactual_simulated',
    controllable: true,
    source: 'Maintenance',
    value: 'Health 72%',
    threshold: '80%',
    description: 'A visible symptom, but replacing it alone only raises predicted yield to 84%.',
    eventIds: ['evt_2292', 'evt_2293', 'evt_2295'],
    evidenceIds: ['evidence-machine-7', 'evidence-machine-sim'],
    position: { x: 37, y: 68 },
  },
  {
    id: 'node_material',
    label: 'Material quality',
    type: 'material',
    influence: 0.05,
    confidence: 0.92,
    evidenceType: 'observed_correlation',
    controllable: false,
    source: 'Materials',
    value: 'Within spec',
    threshold: 'Certified',
    description: 'Intake evidence rules material quality down as a primary factor.',
    eventIds: ['evt_2287', 'evt_2288'],
    evidenceIds: ['evidence-material'],
    position: { x: 10, y: 68 },
  },
  {
    id: 'node_quality_failure',
    label: 'Quality failure',
    type: 'outcome',
    influence: 1,
    confidence: 0.95,
    evidenceType: 'observed_correlation',
    controllable: false,
    source: 'Quality',
    value: 'Score 62.3',
    threshold: '80',
    description: 'The observed outcome: 18% defects and batch rejection.',
    eventIds: ['evt_2293', 'evt_2294', 'evt_2295', 'evt_2296'],
    evidenceIds: ['evidence-inspection'],
    position: { x: 85, y: 43 },
  },
];

export const graphEdges: GraphEdge[] = [
  { id: 'edge-humidity-queue', from: 'node_humidity', to: 'node_queue_delay', strength: 0.42, evidenceType: 'observed_correlation', label: 'contributes' },
  { id: 'edge-queue-temp', from: 'node_queue_delay', to: 'node_temp_drift', strength: 0.78, evidenceType: 'model_estimated', label: 'influences' },
  { id: 'edge-temp-quality', from: 'node_temp_drift', to: 'node_quality_failure', strength: 0.65, evidenceType: 'model_estimated', label: 'mechanism' },
  { id: 'edge-queue-quality', from: 'node_queue_delay', to: 'node_quality_failure', strength: 0.89, evidenceType: 'counterfactual_simulated', label: 'primary' },
  { id: 'edge-machine-quality', from: 'node_machine_7', to: 'node_quality_failure', strength: 0.22, evidenceType: 'counterfactual_simulated', label: 'secondary' },
  { id: 'edge-material-quality', from: 'node_material', to: 'node_quality_failure', strength: 0.05, evidenceType: 'observed_correlation', label: 'weak' },
];

export const evidenceRecords: EvidenceRecord[] = [
  {
    id: 'evidence-batch-start',
    title: 'MES batch genealogy',
    source: 'MES',
    recordId: 'batch:B-2407-184',
    timestamp: at('08:00'),
    kind: 'record',
    summary: 'Route and batch genealogy were initialized normally.',
    confidence: 1,
    evidenceType: 'observed_correlation',
  },
  {
    id: 'evidence-material',
    title: 'Supplier lot certification',
    source: 'Materials',
    recordId: 'lot:LOT-SUP-2407-88',
    timestamp: at('08:05'),
    kind: 'record',
    summary: 'EN31 material passed hardness, certification, and intake-condition checks.',
    confidence: 0.92,
    evidenceType: 'observed_correlation',
  },
  {
    id: 'evidence-machine-a',
    title: 'Machine A process record',
    source: 'MES',
    recordId: 'path:MCHA-2407',
    timestamp: at('08:20'),
    kind: 'record',
    summary: 'Cycle time, feed rate, and speed were inside nominal range.',
    confidence: 0.99,
    evidenceType: 'observed_correlation',
  },
  {
    id: 'evidence-humidity',
    title: 'Queue-area humidity',
    source: 'IoT',
    recordId: 'sensor:HUM-2407-51',
    timestamp: at('08:51'),
    kind: 'sensor',
    summary: 'Humidity reached 68.5% RH, above the material storage ceiling of 60%.',
    confidence: 0.88,
    evidenceType: 'observed_correlation',
  },
  {
    id: 'evidence-queue',
    title: 'MES queue event',
    source: 'MES',
    recordId: 'evt:Q-2407-001',
    timestamp: at('11:38'),
    kind: 'record',
    summary: 'The batch waited 198 minutes between turning and grinding; expected wait was 30 minutes.',
    confidence: 0.96,
    evidenceType: 'observed_correlation',
  },
  {
    id: 'evidence-queue-sim',
    title: 'Queue-delay counterfactual',
    source: 'Simulation',
    recordId: 'sim:run_014',
    timestamp: at('11:49'),
    kind: 'simulation',
    summary: 'Reducing queue delay below 60 minutes restores predicted yield from 82% to 96%.',
    confidence: 0.96,
    evidenceType: 'counterfactual_simulated',
  },
  {
    id: 'evidence-temp',
    title: 'Machine 7 thermal alert',
    source: 'Maintenance',
    recordId: 'alert:MA-2407-013',
    timestamp: at('11:40'),
    kind: 'sensor',
    summary: 'Temperature reached 31.4°C against a 28°C threshold.',
    confidence: 0.82,
    evidenceType: 'model_estimated',
  },
  {
    id: 'evidence-machine-7',
    title: 'Machine 7 vibration alert',
    source: 'Maintenance',
    recordId: 'alert:MA-2407-012',
    timestamp: at('11:42'),
    kind: 'sensor',
    summary: 'Vibration reached 4.7 mm/s against a 3.5 mm/s threshold.',
    confidence: 0.81,
    evidenceType: 'observed_correlation',
  },
  {
    id: 'evidence-machine-sim',
    title: 'Machine replacement counterfactual',
    source: 'Simulation',
    recordId: 'sim:run_015',
    timestamp: at('11:49'),
    kind: 'simulation',
    summary: 'Replacing Machine 7 while leaving queue conditions unchanged only raises predicted yield to 84%.',
    confidence: 0.61,
    evidenceType: 'counterfactual_simulated',
  },
  {
    id: 'evidence-defect-dimensional',
    title: 'Dimensional inspection',
    source: 'Quality',
    recordId: 'defect:DEF-2407-041',
    timestamp: at('11:45'),
    kind: 'record',
    summary: 'Bore diameter was 0.08 mm above tolerance.',
    confidence: 0.97,
    evidenceType: 'observed_correlation',
  },
  {
    id: 'evidence-defect-surface',
    title: 'Surface inspection',
    source: 'Quality',
    recordId: 'defect:DEF-2407-042',
    timestamp: at('11:46'),
    kind: 'record',
    summary: 'Surface roughness measured Ra 0.62 μm against a 0.40 μm limit.',
    confidence: 0.95,
    evidenceType: 'observed_correlation',
  },
  {
    id: 'evidence-inspection',
    title: 'Final inspection result',
    source: 'Quality',
    recordId: 'inspection:INSP-2407-184',
    timestamp: at('11:47'),
    kind: 'record',
    summary: 'Quality score 62.3/100; final batch yield 82%; disposition rejected.',
    confidence: 1,
    evidenceType: 'observed_correlation',
  },
];

export const simulationPresets: Record<string, SimulationResult> = {
  baseline: {
    scenarioId: 'sim:run_001',
    scenarioName: 'Incident baseline',
    baselineYield: 82,
    predictedYield: 82,
    confidence: 0.95,
    cost: 'None',
    effort: 'None',
    assumptions: ['All observed conditions held constant'],
    reasoning: 'No intervention is applied, so the incident yield remains at 82%.',
    inValidatedRange: true,
    warnings: [],
    evidenceRefs: ['timeline:evt_2296'],
    modelVersion: 'forgeops-sim-v1.0',
  },
  reduce_queue_delay: {
    scenarioId: 'sim:run_014',
    scenarioName: 'Reduce queue delay',
    baselineYield: 82,
    predictedYield: 96,
    confidence: 0.96,
    cost: 'Low · ₹15k',
    effort: 'Scheduling change · ~2 hours',
    assumptions: ['Machine 7 condition held constant', 'No supplier change within 30 days', 'Queue wait maintained below 60 minutes'],
    reasoning: 'Queue delay is the strongest controllable cause; reducing it below 60 minutes removes the primary bottleneck without requiring machine replacement.',
    inValidatedRange: true,
    warnings: [],
    evidenceRefs: ['timeline:evt_2291', 'graph:node_queue_delay', 'sim:run_014'],
    modelVersion: 'forgeops-sim-v1.0',
  },
  humidity_control: {
    scenarioId: 'sim:run_016',
    scenarioName: 'Install humidity control',
    baselineYield: 82,
    predictedYield: 96,
    confidence: 0.94,
    cost: 'High · ₹8.5L',
    effort: 'Equipment install · 1–2 weeks',
    assumptions: ['Humidity remains below 55%', 'Machine 7 condition held constant'],
    reasoning: 'Humidity control removes the material-exposure condition observed during the extended queue wait.',
    inValidatedRange: true,
    warnings: [],
    evidenceRefs: ['timeline:evt_2290', 'graph:node_humidity', 'sim:run_016'],
    modelVersion: 'forgeops-sim-v1.0',
  },
  replace_machine_7: {
    scenarioId: 'sim:run_015',
    scenarioName: 'Replace Machine 7',
    baselineYield: 82,
    predictedYield: 84,
    confidence: 0.61,
    cost: 'High · ₹12L',
    effort: 'Disruptive · 2–3 days',
    assumptions: ['Queue delay remains at 198 minutes', 'Humidity conditions remain unchanged'],
    reasoning: 'Machine 7 replacement addresses a weaker causal factor while the dominant queue delay remains unchanged.',
    inValidatedRange: true,
    warnings: ['Replacement alone leaves the dominant queue-delay factor unchanged.'],
    evidenceRefs: ['timeline:evt_2293', 'graph:node_machine_7', 'sim:run_015'],
    modelVersion: 'forgeops-sim-v1.0',
  },
};

export const recommendations: Recommendation[] = [
  {
    id: 'rec-queue',
    rank: 1,
    title: 'Reduce queue delay below 60 minutes',
    confidence: 0.96,
    predictedYield: 96,
    cost: 'Low',
    costInr: 15000,
    effort: 'Easy · ~2 hours',
    impact: 'High',
    risk: 'Low',
    description: 'Adjust dispatch priority between Machine A and Machine 7. Supported by 327 historical batches and the strongest counterfactual result.',
    savingsPerWeekInr: 420000,
    evidenceRefs: ['timeline:evt_2291', 'graph:node_queue_delay', 'sim:run_014'],
  },
  {
    id: 'rec-humidity',
    rank: 2,
    title: 'Install humidity control in the queue area',
    confidence: 0.94,
    predictedYield: 96,
    cost: 'High',
    costInr: 850000,
    effort: 'Medium · 1–2 weeks',
    impact: 'High',
    risk: 'Medium',
    description: 'Maintain less than 55% RH in staging. Effective, but slower and materially more expensive.',
    savingsPerWeekInr: 420000,
    evidenceRefs: ['timeline:evt_2290', 'graph:node_humidity', 'sim:run_016'],
  },
  {
    id: 'rec-machine',
    rank: 3,
    title: 'Replace or overhaul Machine 7',
    confidence: 0.61,
    predictedYield: 84,
    cost: 'High',
    costInr: 1200000,
    effort: 'Disruptive · 2–3 days',
    impact: 'Low',
    risk: 'High',
    description: 'The machine alarm is real, but replacement alone produces only a two-point predicted recovery.',
    savingsPerWeekInr: 50000,
    evidenceRefs: ['timeline:evt_2293', 'graph:node_machine_7', 'sim:run_015'],
  },
];

export const businessImpact: BusinessImpact = {
  currentMonthlyLossInr: 1800000,
  monthlySavingsInr: 1500000,
  downtimeReductionPct: 41,
  baselineYield: 82,
  predictedYield: 96,
  paybackPeriod: 'Immediate — scheduling change',
  basis: 'Simulation sim:run_014 · 327 comparable historical batches',
};

const sharedTrace = [
  { id: 'trace-1', server: 'MES', tool: 'get_queue_events', status: 'complete' as const, durationMs: 124, records: ['evt:Q-2407-001'] },
  { id: 'trace-2', server: 'Quality', tool: 'get_inspection_results', status: 'complete' as const, durationMs: 96, records: ['inspection:INSP-2407-184'] },
  { id: 'trace-3', server: 'Maintenance', tool: 'get_machine_alerts', status: 'complete' as const, durationMs: 108, records: ['alert:MA-2407-012', 'alert:MA-2407-013'] },
  { id: 'trace-4', server: 'Simulation', tool: 'compare_scenarios', status: 'complete' as const, durationMs: 342, records: ['sim:run_014', 'sim:run_015'] },
];

export const assistantResponses: Record<string, AssistantResponse> = {
  evidence: {
    intent: 'show_evidence',
    conclusion: 'Queue delay is the strongest controllable contributor.',
    effect: 'Reducing the wait below 60 minutes restores predicted yield from 82% to 96%.',
    confidence: 0.96,
    evidenceRefs: ['timeline:evt_2291', 'graph:node_queue_delay', 'sim:run_014'],
    assumptions: ['Machine 7 condition held constant', 'No supplier change within 30 days'],
    actions: ['open_evidence', 'run_comparison', 'generate_report'],
    toolTrace: sharedTrace,
    uiActions: [],
    generatedReports: [],
    notifications: [],
  },
  machine: {
    intent: 'explain_exclusion',
    conclusion: 'Machine 7 is a contributor, but not the primary cause.',
    effect: 'Replacement alone improves predicted yield by only 2 points, compared with 14 points from queue-delay reduction.',
    confidence: 0.87,
    evidenceRefs: ['timeline:evt_2293', 'graph:node_machine_7', 'sim:run_015'],
    assumptions: ['Queue delay remains at 198 minutes', 'Humidity conditions remain unchanged'],
    actions: ['open_evidence', 'run_comparison', 'generate_report'],
    toolTrace: sharedTrace,
    uiActions: [],
    generatedReports: [],
    notifications: [],
  },
  compare: {
    intent: 'compare_options',
    conclusion: 'Reduce queue delay first; it matches humidity control’s predicted yield at a fraction of the cost.',
    effect: '96% predicted yield, ₹15k implementation cost, and approximately two hours to deploy.',
    confidence: 0.94,
    evidenceRefs: ['graph:node_queue_delay', 'sim:run_014', 'sim:run_016', 'sim:run_015'],
    assumptions: ['Current production schedule can be reprioritized', 'Supplier freeze remains active'],
    actions: ['open_evidence', 'run_comparison', 'generate_report'],
    toolTrace: sharedTrace,
    uiActions: [],
    generatedReports: [],
    notifications: [],
  },
  report: {
    intent: 'generate_report',
    conclusion: 'The plant-manager decision brief is ready for review.',
    effect: 'It packages the incident, evidence chain, scenario comparison, recommendation, impact, and approval record.',
    confidence: 0.96,
    evidenceRefs: ['timeline:evt_2291', 'graph:node_queue_delay', 'sim:run_014'],
    assumptions: ['Report remains a draft until an authorized manager approves it'],
    actions: ['open_evidence', 'generate_report'],
    toolTrace: sharedTrace,
    uiActions: [],
    generatedReports: [],
    notifications: [],
  },
};

export const sensorSeries = {
  humidity: [48, 50, 54, 59, 63, 68.5, 68.2, 67],
  queue: [0, 12, 30, 58, 96, 132, 168, 198],
  referenceHumidity: [43, 44, 43, 45, 44, 43, 42, 43],
};
